---
- name: Add dynamic hosts from survey
  hosts: localhost
  gather_facts: false
  vars:
    service_name: "{{ service_name }}"
    survey_hosts: "{{ hosts_list.split(',') }}" 
  tasks:
    - name: Add hosts dynamically (hostname from survey, IP resolved via vCenter inventory)
      add_host:
        name: "{{ item }}"
        groups: dynamic_hosts
      loop: "{{ survey_hosts }}"

- name: Verify service status on all hosts
  hosts: dynamic_hosts
  become: yes
  gather_facts: false
  vars:
    service_name: "{{ service_name }}"
  tasks:
    - name: Check service status
      ansible.builtin.systemd:
        name: "{{ service_name }}"
        state: started
      register: service_status

    - name: Show service status
      debug:
        msg: "{{ inventory_hostname }} (IP: {{ hostvars[inventory_hostname].ansible_host }}): {{ service_name }} is {{ 'running' if service_status.status.ActiveState == 'active' else 'stopped' }}"
