---
- name: Create user dynamically from AWX
  hosts: ansible_host
  become: yes

  tasks:
    - name: Create user with password and shell
      ansible.builtin.user:
        name: "{{ user_name }}"
        password: "{{ user_password | password_hash('sha512') }}"
        shell: /bin/bash
        state: present

    - name: Add user to group
      ansible.builtin.user:
        name: "{{ user_name }}"
        groups: "{{ group_name_user }}"
        append: yes